### PR TITLE
Test small change

### PR DESCRIPTION
**Pull request by louis-galipeau**
Test cancel this pull request as this was just to test if I could see my changes on my fork.

### CODE REVIEW

**Comment by MaximMartel** [comment]
avez-vous changez quelquechose?

**Comment by louis-galipeau** [comment]
Just my name in the schedule on the french page.

**Comment by louis-galipeau** [comment]
I was trying to figure out how to use github so please cancel the pull request.

**Comment by MaximMartel** [comment]
ok understood, will cancel this PR

**Pull request closed without merging**
